# Default values for settings.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  #Add your custom built docker image
  repository: vikram412/expressCart
  tag: latest
  pullPolicy: Always

#project env
projectEnv:
  NODE_ENV: "development"
  NODE_PATH: "/"
  MONGODB_URI: "mongodb://root:expressCart@mongodb.expresscart.svc.cluster.local/expresscart"

service:
  name: expressCart
  tier: backend
  type: ClusterIP
  externalPort: 80
  internalPort: 1111

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - expresscart.example.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "200M"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "500s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500s"
    kubernetes.io/ingress.class: nginx
    #Used to create tls certificates automatically using cert-manager
    cert-manager.io/issuer: "letsencrypt-prod"
  tls:
    # Secrets will be automatically created in the namespace.
    - secretName: expressCart-tls
      hosts:
        - expresscart.example.com
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 500m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
